#-------------------------------
# General Site Settings

menu:
- {name: 'Home', url: ''}
- {name: 'Blog', url: 'pages/news.html'} #renamed blog to news
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'J. Berenike Herrmann'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Dr. J. Berenike Herrmann

  Welcome to my personal webpage!

contact: >
  # Contact

  Contact me via [my email](mailto:berenike.herrmann@unibas.ch) or [tweet at me](https://twitter.com/intent/tweet?text=%40jberenike).

#-------------------------------
# Work Section

projects:
- {name: 'About', folder: 'about', file: 'projects/about.html'}
- {name: 'CV', folder: 'cv', file: 'projects/cv.html'}
- {name: 'Publications', folder: 'publications', file: 'projects/publications.html'}
- {name: 'News', folder: 'news', file: 'projects/news.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: '#'}
- {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
